import product1 from "./assets/products/product3.png";

const PRODUCTS = [
  {
    id: 1,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 1",
    productImage: product1,
    rating: 4,
    category: "type1",
  },
  {
    id: 2,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 4",
    productImage: product1,
    rating: 4,
    category: "type1",
  },
  {
    id: 3,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 3",
    productImage: product1,
    rating: 4,
    category: "type1",
  },
  {
    id: 4,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 1",
    productImage: product1,
    rating: 4,
    category: "type1",
  },
  {
    id: 5,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type2",
  },
  {
    id: 6,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type3",
  },
  {
    id: 7,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type4",
  },
  {
    id: 8,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type3",
  },
  {
    id: 9,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type4",
  },
  {
    id: 10,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type2",
  },
  {
    id: 11,
    productName: "Headphone",
    price: 999.0,
    desc: "Wireless Bluetooth headphone 2",
    productImage: product1,
    rating: 4,
    category: "type4",
  },
];

export default PRODUCTS;
